### ISSUE TITLE
GRAYLOG_TIMEZONE not affecting graylog server timezone

### ISSUE THREAD

**Issue by mariaczi** [Graylog2/graylog-docker#113]
docker image: 3.1.4 (the same on version 3.1.3)

Using GRAYLOG_TIMEZONE env option not affecting graylog timezone which we can see on "System/Overview" via WebGUI as "Graylog server:" in "Time configuration" section.

So to fix the timezone settings I used
`GRAYLOG_SERVER_JAVA_OPTS=-Duser.timezone=Europe/Warsaw`
which have impact on earlier mentioned timezone settings for graylog server.

**Comment by jalogisch** [comment]
he @mariaczi 

There is not setting `TIMEZONE` in Graylog so that `GRAYLOG_TIMEZONE` can't change anything. Where did you have the information from that this will change Graylogs time?

When you refer to `root_timezone` - that is only the time for the build in admin user. As written in the documentation: http://docs.graylog.org/en/3.1/pages/configuration/server.conf.html#general

Could you please clarify.

**Comment by mariaczi** [comment]
Hi @jalogisch 
I found option GRAYLOG_TIMEZONE here: https://docs.graylog.org/en/1.3/pages/installation/docker.html It is of course my mistake. I'm not saw that was for the very old version of graylog-docker. For the current/latest version this option is not available.
Regards.

**Comment by jalogisch** [comment]
👍 

I'll close this now.
