### ISSUE TITLE
Extend example docker-compose.yml with timezone

### ISSUE THREAD

**Issue by Nebucatnetzer** [Graylog2/graylog-docker#126]
It would be nice if the example would include the configuration of the timezone for the server.
E.g. something like this: https://serverfault.com/a/854685

**Comment by asachs01** [comment]
@Nebucatnetzer can you elaborate more on why you'd like to see the example include something like this? Is there a particular problem you're having with timezones, or a use case that you can tell us more about?

**Comment by Nebucatnetzer** [comment]
Not specifically we just noticed that the server had the "wrong" timezone and found that this was to way to fix it.

**Comment by asachs01** [comment]
Hmmmmm...my personal feeling is that including something like that is highly environment specific and seems to be fixing a problem that not everyone is running into. Or at the very least, we've not had reports of other users who have found the lack of timezones included in the example Docker compose file to be an issue. It's also worth noting that the example is just that--to take Graylog into production with just the example compose file is ill-advised and so you'll necessarily need to make any adjustments necessary so that what's being deployed in your environment is production ready. I'm happy to defer to @jalogisch @dennisoelkers or some of the other members of the team for their input as this is just my take.

**Comment by Nebucatnetzer** [comment]
I don't really care that much about it just something I thought might be worth to be added.
I'm fine with either decision.

In general I think a lot of examples could get extended for Docker anyway. I imagine that more and more people will install Graylog that way instead of a normal installation.
This just as a sidenote.

**Comment by asachs01** [comment]
Hi there, 

After reviewing with the team, we've decided that we won't be extending the examples with additional environmental settings. Given that the end goal in providing examples for the Docker image is to provide a baseline that all users can start working from, we consider it out of scope to account for environmental settings that are specific to an environment.
