### ISSUE TITLE
Image for arm64 architecture tag problem

### ISSUE THREAD

**Issue by danielporto** [Graylog2/graylog-docker#175]
The arm64 images currently provided under a different tag in dockerhub,
namely 4.1.3-arm64 instead of simply 4.1.3 with multiarch support.
This is problematic because dockerfiles, stack or compose files are not meant to 
declare the system architecture when downloading a stack.
Thus, we need to keep two different files (one with each tag) just to be able to deploy it in different architectures - ex amazon arm64 and and x86_64 instances. 

As exemplified by [this comment in issue 153](https://github.com/Graylog2/graylog-docker/issues/163#issuecomment-887758323) is it possible to have the same tag for multiple architectures using buildx.

It would really be nice to have the same stack file for both architectures.

**Comment by juju2112** [comment]
I agree that this would be good. However, it would mean we would have to move our build pipeline off of Docker Hub, since Docker Hub doesn't support ARM builds. And we're pretty happy with Docker Hub, other than this one thing. 

I have a Jenkins job set up to do the multiarch build, but right now it's just building the arm image. I think we want to see how stable that job is an if it gives us any problems before we consider migrating the Docker Hub stuff to it.

**Comment by malcyon** [comment]
Our images are now multiarch, and I've updated the README with the details. We won't be using the `-arm64` tags going forward.

**Comment by malcyon** [comment]
Alright, I fixed the 4.1 images as well. Multiarch images are present in `4.2` and `4.1` now.
